__version__ = '0.1.1'
__author__ = 'Loris Henrion'
__author_email__ = 'loris_henrion@bce.lu'
__description__ = 'Syncing custom permissions (tenant) on objects with those from their corresponding parent object in NetBox'
__license__ = 'GPL-3.0'
__url__ = 'https://github.com/LoH-lu/netbox_custom_permissions_synchronization/'
